# This manifest creates a primary user defined network (UDN) in a Layer-2 topology with a subnet of 10.0.0.0/24

apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-1
  namespace: my_namespace
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - "10.0.0.0/24"
