# This is a NodeNetworkConfigurationPolicy which creates a new OVS bridge called "ovs-br1" and assigns the bond0 interface as a port

apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-bridge
spec:
  desiredState:
    interfaces:
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp: false
          port:
            - name: bond0
        description: |-
          A dedicated OVS bridge with bond0 as a port
          allowing all VLANs and untagged traffic
        name: ovs-br1
        state: up
        type: ovs-bridge
